application: kan-udacity
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  
- url: /
  script: home.app

- url: /rot13
  script: rot13.app

- url: /blog.*
  script: blog.app

- url: /wiki.*
  script: wiki.app

#- url: /blog/signup
#  script: signup.app

#- url: /blog/welcome
#  script: signup.app

#- url: /blog/newpost
#  script: blog.app

#- url: /blog/(\d+)
#  script: blog.app

libraries:
- name: jinja2
  version: latest

