application: kan-udacity
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: home.app

- url: /rot13
  script: rot13.app

- url: /signup
  script: signup.app

- url: /welcome
  script: signup.app

- url: /blog
  script: blog.app

- url: /blog/newpost
  script: blog.app

- url: /blog/(\d+)
  script: blog.app

- url: /stylesheets
  static_dir: stylesheets

libraries:
- name: jinja2
  version: latest

