application: kan-udacity
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: home.app

- url: /unit2/rot13
  script: rot13.app

- url: /unit2/signup
  script: signup.app

