application: kan-udacity
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: home.app

- url: /rot13
  script: rot13.app

- url: /signup
  script: signup.app

- url: /welcome
  script: signup.app
